name: C CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Test Suite
      run: make -C ./test/main nocov
