name: Test Suit

on:
  push:
    branches: [ master, dev ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: sudo apt install make valgrind gcc
    - name: Versions
      run: |
        gcc --version \
        make --version \
        valgrind --version \
    - name: Test Suite
      run: make tests --always-make
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        directory: ./tests
        verbose: true
